<template>
  <div>
    <ModuleTable title="轮播图管理" description="维护商家端展示图、排序、跳转链接和启停状态。" :columns="columns" :rows="banners" :keyword-fields="['title', 'position']" secondary-action-text="保存排序" danger-action-text="删除" row-action-text="编辑" />
    <div class="page-actions"><el-button type="primary" @click="dialogVisible=true">新建轮播图</el-button></div>
    <el-dialog v-model="dialogVisible" title="新建轮播图" width="720px"><el-form ref="formRef" :model="form" :rules="rules" label-position="top" :disabled="submitLoading"><el-row :gutter="16"><el-col :span="12"><el-form-item label="所属应用" prop="app"><el-select v-model="form.app"><el-option label="优洗生活商家端" value="merchant" /><el-option label="小程序" value="mini" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="名称" prop="name"><el-input v-model="form.name" /></el-form-item></el-col><el-col :span="12"><el-form-item label="类型" prop="type"><el-select v-model="form.type"><el-option label="首页轮播" value="home" /><el-option label="活动入口" value="activity" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="跳转链接"><el-input v-model="form.url" /></el-form-item></el-col><el-col :span="12"><el-form-item label="开始时间"><el-date-picker v-model="form.dateRange" type="daterange" style="width:100%" /></el-form-item></el-col><el-col :span="12"><el-form-item label="排序"><el-input-number v-model="form.sort" :min="0" style="width:100%" /></el-form-item></el-col></el-row><el-form-item label="图片"><div class="upload-box">单击上传</div></el-form-item><el-form-item label="状态" prop="status"><el-select v-model="form.status"><el-option label="启用" value="online" /><el-option label="停用" value="offline" /></el-select></el-form-item><el-form-item label="备注"><el-input v-model="form.remark" type="textarea" maxlength="200" show-word-limit /></el-form-item></el-form><template #footer><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" :loading="submitLoading" @click="submit">确定</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts">
import { reactive, ref } from 'vue'; import { ElMessage, type FormInstance, type FormRules } from 'element-plus'; import ModuleTable from '@/components/business/ModuleTable.vue'; import { banners, statusMaps } from '@/mock/modules/module-data'; import type { TableColumnConfig } from '@/types/module'
const dialogVisible=ref(false); const submitLoading=ref(false); const formRef=ref<FormInstance>(); const form=reactive({app:'',name:'',type:'',url:'',dateRange:[],sort:0,status:'online',remark:''}); const rules:FormRules={app:[{required:true,message:'请选择所属应用',trigger:'change'}],name:[{required:true,message:'请输入名称',trigger:'blur'}],type:[{required:true,message:'请选择类型',trigger:'change'}],status:[{required:true,message:'请选择状态',trigger:'change'}]}
const columns: TableColumnConfig[]=[{prop:'sort',label:'排序',width:90,type:'number'},{prop:'id',label:'ID',width:120},{prop:'position',label:'应用名',width:130},{prop:'title',label:'名称',minWidth:160},{prop:'status',label:'状态',width:100,type:'status',statusMap:statusMaps.publish},{prop:'updatedAt',label:'修改时间',width:130}]
async function submit(){ if(submitLoading.value)return; await formRef.value?.validate(); submitLoading.value=true; try{ await new Promise(r=>setTimeout(r,600)); ElMessage.success('轮播图保存成功'); dialogVisible.value=false } finally{ submitLoading.value=false } }
</script>
<style scoped>.page-actions{display:flex;justify-content:flex-end;margin:12px 0}.upload-box{width:104px;height:104px;display:grid;place-items:center;border:1px dashed var(--yx-border);border-radius:var(--yx-radius-md);color:var(--yx-text-regular);background:#fafcff}</style>
