<template>
  <div>
    <ModuleTable title="网店商品" description="管理商家端展示商品、库存、价格和上下架状态。" :columns="columns" :rows="products" :keyword-fields="['name','sku','category']" secondary-action-text="批量上下架" danger-action-text="删除" row-action-text="编辑" />
    <div class="page-actions"><el-button type="primary" @click="dialogVisible=true">新增商品</el-button></div>
    <el-dialog v-model="dialogVisible" title="新增商品" width="720px"><el-form ref="formRef" :model="form" :rules="rules" label-position="top" :disabled="submitLoading"><el-row :gutter="16"><el-col :span="12"><el-form-item label="商品名称" prop="name"><el-input v-model="form.name" /></el-form-item></el-col><el-col :span="12"><el-form-item label="SKU" prop="sku"><el-input v-model="form.sku" /></el-form-item></el-col><el-col :span="12"><el-form-item label="类目"><el-select v-model="form.category"><el-option label="鞋靴" value="鞋靴" /><el-option label="服装" value="服装" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="价格"><el-input v-model="form.price" /></el-form-item></el-col><el-col :span="12"><el-form-item label="库存"><el-input-number v-model="form.stock" :min="0" style="width:100%" /></el-form-item></el-col><el-col :span="12"><el-form-item label="状态"><el-select v-model="form.status"><el-option label="上架" value="online" /><el-option label="下架" value="offline" /></el-select></el-form-item></el-col></el-row><el-form-item label="商品图"><div class="upload-box">单击上传</div></el-form-item></el-form><template #footer><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" :loading="submitLoading" @click="submit">确定</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts">
import { reactive, ref } from 'vue'; import { ElMessage, type FormInstance, type FormRules } from 'element-plus'; import ModuleTable from '@/components/business/ModuleTable.vue'; import { products, statusMaps } from '@/mock/modules/module-data'; import type { TableColumnConfig } from '@/types/module'
const dialogVisible=ref(false); const submitLoading=ref(false); const formRef=ref<FormInstance>(); const form=reactive({name:'',sku:'',category:'',price:'',stock:0,status:'online'}); const rules:FormRules={name:[{required:true,message:'请输入商品名称',trigger:'blur'}],sku:[{required:true,message:'请输入SKU',trigger:'blur'}]}
const columns: TableColumnConfig[]=[{prop:'name',label:'商品名称',minWidth:180},{prop:'sku',label:'SKU',width:140},{prop:'category',label:'类目',width:100},{prop:'price',label:'价格',width:100,type:'money'},{prop:'stock',label:'库存',width:90,type:'number'},{prop:'status',label:'状态',width:100,type:'status',statusMap:statusMaps.publish}]
async function submit(){ if(submitLoading.value)return; await formRef.value?.validate(); submitLoading.value=true; try{ await new Promise(r=>setTimeout(r,600)); ElMessage.success('商品保存成功'); dialogVisible.value=false } finally{ submitLoading.value=false } }
</script>
<style scoped>.page-actions{display:flex;justify-content:flex-end;margin:12px 0}.upload-box{width:120px;height:120px;display:grid;place-items:center;border:1px dashed var(--yx-border);border-radius:var(--yx-radius-md);color:var(--yx-text-regular);background:#fafcff}</style>
