<template>
  <div>
    <ModuleTable title="类目管理" description="维护洗护商品类目、归属品牌、归属应用、排序和状态。" :columns="columns" :rows="categories" :keyword-fields="['name', 'parent']" secondary-action-text="保存排序" danger-action-text="删除" row-action-text="编辑" />
    <div class="page-actions"><el-button type="primary" @click="dialogVisible=true">新建类目</el-button></div>
    <el-dialog v-model="dialogVisible" title="新建类目" width="640px"><el-form ref="formRef" :model="form" :rules="rules" label-position="top" :disabled="submitLoading"><el-row :gutter="16"><el-col :span="12"><el-form-item label="归属品牌" prop="brand"><el-select v-model="form.brand"><el-option label="优洗生活" value="优洗生活" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="归属应用" prop="app"><el-select v-model="form.app"><el-option label="商家端" value="merchant" /><el-option label="小程序" value="mini" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="上级类目"><el-select v-model="form.parent"><el-option label="无" value="" /><el-option label="鞋靴" value="鞋靴" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="类目名称" prop="name"><el-input v-model="form.name" /></el-form-item></el-col><el-col :span="12"><el-form-item label="排序"><el-input-number v-model="form.sort" :min="0" style="width:100%" /></el-form-item></el-col><el-col :span="12"><el-form-item label="状态" prop="status"><el-select v-model="form.status"><el-option label="启用" value="online" /><el-option label="停用" value="offline" /></el-select></el-form-item></el-col></el-row></el-form><template #footer><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" :loading="submitLoading" @click="submit">确定</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts">
import { reactive, ref } from 'vue'; import { ElMessage, type FormInstance, type FormRules } from 'element-plus'; import ModuleTable from '@/components/business/ModuleTable.vue'; import { categories, statusMaps } from '@/mock/modules/module-data'; import type { TableColumnConfig } from '@/types/module'
const dialogVisible=ref(false); const submitLoading=ref(false); const formRef=ref<FormInstance>(); const form=reactive({brand:'',app:'',parent:'',name:'',sort:0,status:'online'}); const rules:FormRules={brand:[{required:true,message:'请选择品牌',trigger:'change'}],app:[{required:true,message:'请选择应用',trigger:'change'}],name:[{required:true,message:'请输入类目名称',trigger:'blur'}],status:[{required:true,message:'请选择状态',trigger:'change'}]}
const columns: TableColumnConfig[]=[{prop:'sort',label:'排序',width:90,type:'number'},{prop:'name',label:'类目名称',minWidth:160},{prop:'parent',label:'上级类目',width:120},{prop:'brand',label:'品牌',width:120},{prop:'app',label:'归属应用',width:120},{prop:'status',label:'状态',width:100,type:'status',statusMap:statusMaps.enabled}]
async function submit(){ if(submitLoading.value)return; await formRef.value?.validate(); submitLoading.value=true; try{ await new Promise(r=>setTimeout(r,600)); ElMessage.success('类目保存成功'); dialogVisible.value=false } finally{ submitLoading.value=false } }
</script>
<style scoped>.page-actions{display:flex;justify-content:flex-end;margin:12px 0}</style>
