<template>
  <div>
    <ModuleTable title="品牌管理" description="维护品牌租户、标识、Logo、商品标识和启停状态。" :columns="columns" :rows="brands" :keyword-fields="['code','name']" secondary-action-text="导出品牌" danger-action-text="禁用" row-action-text="修改" />
    <div class="page-actions"><el-button type="primary" @click="dialogVisible=true">新增品牌</el-button></div>
    <el-dialog v-model="dialogVisible" title="新建品牌" width="720px"><el-form ref="formRef" :model="form" :rules="rules" label-position="top" :disabled="submitLoading"><el-row :gutter="16"><el-col :span="12"><el-form-item label="租户" prop="tenant"><el-select v-model="form.tenant"><el-option label="D0174-北京盛峰雅洁清洗服务有限公司" value="D0174" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="名称" prop="name"><el-input v-model="form.name" /></el-form-item></el-col><el-col :span="12"><el-form-item label="标识" prop="code"><el-input v-model="form.code" /></el-form-item></el-col><el-col :span="12"><el-form-item label="指定件数计费"><el-switch v-model="form.pieceBilling" /></el-form-item></el-col><el-col :span="12"><el-form-item label="合并门店用户和小程序用户"><el-switch v-model="form.mergeUser" /></el-form-item></el-col><el-col :span="12"><el-form-item label="鞋子商品标识"><el-select v-model="form.shoeTag"><el-option label="鞋类" value="shoe" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="奢洗标识"><el-select v-model="form.luxuryTag"><el-option label="奢洗" value="luxury" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="修复标识"><el-select v-model="form.repairTag"><el-option label="修复" value="repair" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="小件标识"><el-select v-model="form.smallTag"><el-option label="小件" value="small" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="其他标识"><el-select v-model="form.otherTag"><el-option label="其他" value="other" /></el-select></el-form-item></el-col></el-row><el-form-item label="logo"><div class="upload-box">单击上传</div></el-form-item><el-row :gutter="16"><el-col :span="12"><el-form-item label="工厂取消拦截" prop="cancelBlock"><el-select v-model="form.cancelBlock"><el-option label="启用" value="enabled" /><el-option label="停用" value="disabled" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="美团核销时间" prop="meituanVerify"><el-select v-model="form.meituanVerify"><el-option label="下单时" value="order" /><el-option label="完成时" value="done" /></el-select></el-form-item></el-col></el-row><el-form-item label="状态" prop="status"><el-select v-model="form.status"><el-option label="启用" value="enabled" /><el-option label="禁用" value="disabled" /></el-select></el-form-item><el-form-item label="备注"><el-input v-model="form.remark" type="textarea" maxlength="200" show-word-limit /></el-form-item></el-form><template #footer><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" :loading="submitLoading" @click="submit">确定</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts">
import { reactive, ref } from 'vue'; import { ElMessage, type FormInstance, type FormRules } from 'element-plus'; import ModuleTable from '@/components/business/ModuleTable.vue'; import { brands, statusMaps } from '@/mock/modules/module-data'; import type { TableColumnConfig } from '@/types/module'
const dialogVisible=ref(false); const submitLoading=ref(false); const formRef=ref<FormInstance>(); const form=reactive({tenant:'D0174',name:'',code:'',pieceBilling:false,mergeUser:false,shoeTag:'',luxuryTag:'',repairTag:'',smallTag:'',otherTag:'',cancelBlock:'',meituanVerify:'',status:'enabled',remark:''}); const rules:FormRules={tenant:[{required:true,message:'请选择租户',trigger:'change'}],name:[{required:true,message:'请输入名称',trigger:'blur'}],code:[{required:true,message:'请输入标识',trigger:'blur'}],cancelBlock:[{required:true,message:'请选择工厂取消拦截',trigger:'change'}],meituanVerify:[{required:true,message:'请选择美团核销时间',trigger:'change'}],status:[{required:true,message:'请选择状态',trigger:'change'}]}
const columns: TableColumnConfig[]=[{prop:'code',label:'ID',width:130},{prop:'name',label:'名称',minWidth:160},{prop:'merchantCount',label:'商户数',width:100,type:'number'},{prop:'productCount',label:'商品数',width:100,type:'number'},{prop:'status',label:'状态',width:100,type:'status',statusMap:statusMaps.enabled},{prop:'updatedAt',label:'修改时间',width:130}]
async function submit(){ if(submitLoading.value)return; await formRef.value?.validate(); submitLoading.value=true; try{ await new Promise(r=>setTimeout(r,650)); ElMessage.success('品牌保存成功'); dialogVisible.value=false } finally{ submitLoading.value=false } }
</script>
<style scoped>.page-actions{display:flex;justify-content:flex-end;margin:12px 0}.upload-box{width:104px;height:104px;display:grid;place-items:center;border:1px dashed var(--yx-border);border-radius:var(--yx-radius-md);background:#fafcff;color:var(--yx-text-regular)}</style>
